### ISSUE TITLE
Can't fetch the BTC RPC Explorer API from a script

### ISSUE THREAD

**Issue by tutacrypto** [getumbrel/umbrel-apps#313]
### Issue
I am trying to get info from `http://umbrel.local:3002/api/block/765088`, but when running `requests.get('http://umbrel.local:3002/api/block/765088')` on my Python script on my desktop (running on the same desktop), I get a <response 200>  and the following error when trying to print it: 

```
Traceback (most recent call last):
  File "/Users/gustave/Desktop/crypto/bitcoin:lightning/projects/bitcoin-sb/main.py", line 12, in <module>
    print(response.json())
  File "/Users/gustave/Library/Python/3.9/lib/python/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] <!DOCTYPE html><html lang="en"><head><title>Umbrel</title><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex, nofollow"><meta name="referrer" content="no-referrer"><link rel="icon" href="favicon.png"><meta name="description" content="Welcome back"><link href="/css/app.65f6aa45.css" rel="preload" as="style"><link href="/js/app.ab94624e.js" rel="preload" as="script"><link href="/js/chunk-vendors.5ff0ba32.js" rel="preload" as="script"><link href="/css/app.65f6aa45.css" rel="stylesheet"></head><body><noscript><strong>We're sorry but Umbrel doesn't work properly without JavaScript enabled. Please enable it to continue.</strong></noscript><div id="app"></div><script src="/js/chunk-vendors.5ff0ba32.js"></script><script src="/js/app.ab94624e.js"></script></body></html>: 0
```

Any ideas? 
Thanks!

Ps: I can print the output of the 3006 API (mempool.space) just fine but it doesn't have the info I'm looking for.

**Comment by nevets963** [comment]
@tutacrypto I managed to replicate this issue and it's because the Umbrel App Proxy (which protects all apps using your password [and where applicable 2FA]) stops unauthorised access to your apps. There are other apps where they whitelist e.g. `/api/*` for the app because they have their own auth. system for the API, but it doesn't look like BTC RPC Explorer has this?

So as alternative, you can whitelist `/api/*` yourself:

SSH into your Umbrel:
```
ssh umbrel@umbrel.local    (or the IP of your Umbrel server)      Password is the same as Umbrel Web UI
```

Run:
```
echo "PROXY_AUTH_WHITELIST=/api/*" >> ~/umbrel/app-data/btc-rpc-explorer/.env.app_proxy
```

Finally, run this command to restart BTC RPC Explorer:
```
sudo ~/umbrel/scripts/app restart btc-rpc-explorer
```

**Comment by tutacrypto** [comment]
I will try this when I get back and keep you posted, thank you!

**Comment by tutacrypto** [comment]
It worked, thank you @nevets963 🙂
